/*
    IMPORTANT! This file is auto-generated by the Projucer or CMake.
    If you need to modify it, do so through your build system configuration.
*/

#pragma once

#ifndef  JucePlugin_Build_VST3
 #define JucePlugin_Build_VST3              1
#endif
#ifndef  JucePlugin_Build_AU
 #define JucePlugin_Build_AU                1
#endif
#ifndef  JucePlugin_Build_Standalone
 #define JucePlugin_Build_Standalone        1
#endif

#ifndef  JucePlugin_Name
 #define JucePlugin_Name                    "Stereo Imager"
#endif
#ifndef  JucePlugin_Desc
 #define JucePlugin_Desc                    "Stereo width and imaging plugin"
#endif
#ifndef  JucePlugin_Manufacturer
 #define JucePlugin_Manufacturer            "Ian Fletcher"
#endif
#ifndef  JucePlugin_ManufacturerWebsite
 #define JucePlugin_ManufacturerWebsite     ""
#endif
#ifndef  JucePlugin_ManufacturerEmail
 #define JucePlugin_ManufacturerEmail       ""
#endif
#ifndef  JucePlugin_ManufacturerCode
 #define JucePlugin_ManufacturerCode        0x49466c74 // 'IFlt'
#endif
#ifndef  JucePlugin_PluginCode
 #define JucePlugin_PluginCode              0x53744967 // 'StIg'
#endif
#ifndef  JucePlugin_IsSynth
 #define JucePlugin_IsSynth                 0
#endif
#ifndef  JucePlugin_WantsMidiInput
 #define JucePlugin_WantsMidiInput          0
#endif
#ifndef  JucePlugin_ProducesMidiOutput
 #define JucePlugin_ProducesMidiOutput      0
#endif
#ifndef  JucePlugin_IsMidiEffect
 #define JucePlugin_IsMidiEffect            0
#endif
#ifndef  JucePlugin_EditorRequiresKeyboardFocus
 #define JucePlugin_EditorRequiresKeyboardFocus  0
#endif
#ifndef  JucePlugin_Version
 #define JucePlugin_Version                 1.0.0
#endif
#ifndef  JucePlugin_VersionCode
 #define JucePlugin_VersionCode             0x10000
#endif
#ifndef  JucePlugin_VersionString
 #define JucePlugin_VersionString           "1.0.0"
#endif
#ifndef  JucePlugin_VSTUniqueID
 #define JucePlugin_VSTUniqueID             JucePlugin_PluginCode
#endif
#ifndef  JucePlugin_VSTCategory
 #define JucePlugin_VSTCategory             kPlugCategEffect
#endif
#ifndef  JucePlugin_Vst3Category
 #define JucePlugin_Vst3Category            "Fx|Spatial"
#endif
#ifndef  JucePlugin_AUMainType
 #define JucePlugin_AUMainType              'aufx'
#endif
#ifndef  JucePlugin_AUSubType
 #define JucePlugin_AUSubType               JucePlugin_PluginCode
#endif
#ifndef  JucePlugin_AUExportPrefix
 #define JucePlugin_AUExportPrefix          StereoImagerAU
#endif
#ifndef  JucePlugin_AUExportPrefixQuoted
 #define JucePlugin_AUExportPrefixQuoted    "StereoImagerAU"
#endif
#ifndef  JucePlugin_AUManufacturerCode
 #define JucePlugin_AUManufacturerCode      JucePlugin_ManufacturerCode
#endif
#ifndef  JucePlugin_CFBundleIdentifier
 #define JucePlugin_CFBundleIdentifier      com.ianfletcher.stereoimager
#endif
#ifndef  JucePlugin_AAXIdentifier
 #define JucePlugin_AAXIdentifier           com.ianfletcher.stereoimager
#endif
#ifndef  JucePlugin_AAXManufacturerCode
 #define JucePlugin_AAXManufacturerCode     JucePlugin_ManufacturerCode
#endif
#ifndef  JucePlugin_AAXProductId
 #define JucePlugin_AAXProductId            JucePlugin_PluginCode
#endif
#ifndef  JucePlugin_AAXCategory
 #define JucePlugin_AAXCategory             0
#endif
#ifndef  JucePlugin_AAXDisableBypass
 #define JucePlugin_AAXDisableBypass        0
#endif
#ifndef  JucePlugin_AAXDisableMultiMono
 #define JucePlugin_AAXDisableMultiMono     0
#endif
